project:
  type: website

website:
  title: "LC"
  site-url: https://psaraki.xyz/
  navbar:
    left:
      - text: about
        href: index.Rmd
      - text: blog
        href: blog.qmd
      - text: apps
        href: apps.qmd
      - text: publications
        href: blog.qmd
        
format:
  html:
    theme: simplex
    fontsize: 1.1em
    page-layout: article
    css: styles.css

editor: source


